elephantly_og_homepage:
    path: /testing_og
    defaults:
        _controller: elephantly.og_object.controller:createAction
        _elephantly:
            template: ElephantlyResourceBundle::test.html.twig
