<?php

namespace Elephantly\OGBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PouetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PouetRepository extends EntityRepository
{
}
